/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream one evidence-grounded chat response
         * @description SSE event order: meta, zero or more citation events, token events, then final. Failures detected before streaming use the stable JSON ErrorResponse contract.
         */
        post: operations["chat_stream_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChatFinalEvent */
        ChatFinalEvent: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            model: components["schemas"]["ModelInfo"];
            /** Request Id */
            request_id: string;
            /**
             * Route
             * @enum {string}
             */
            route: "nutrition" | "platform" | "mixed" | "out_of_scope";
            safety: components["schemas"]["SafetyResult"];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Conversation Id */
            conversation_id: string;
            /** Message */
            message: string;
            profile_patch?: components["schemas"]["ProfilePatch"] | null;
        };
        /** Citation */
        Citation: {
            /** Chunk Id */
            chunk_id: string;
            /** Excerpt */
            excerpt: string;
            /** Page */
            page: number;
            /** Section */
            section: string;
            /**
             * Source
             * @enum {string}
             */
            source: "A" | "B" | "C";
            /** Title */
            title: string;
        };
        /** ComponentStatus */
        ComponentStatus: {
            /** Detail */
            detail?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "configured" | "mock" | "not_configured" | "not_checked" | "disabled";
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
            /** Retryable */
            retryable: boolean;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Dependencies */
            dependencies: {
                [key: string]: components["schemas"]["ComponentStatus"];
            };
            /**
             * Environment
             * @enum {string}
             */
            environment: "development" | "test" | "production";
            /** Modes */
            modes: {
                [key: string]: string;
            };
            /** Request Id */
            request_id: string;
            /**
             * Service
             * @default healthpick-api
             * @constant
             */
            service: "healthpick-api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** ModelInfo */
        ModelInfo: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "real" | "mock";
            /** Name */
            name: string;
            /** Provider */
            provider: string;
        };
        /** ProfilePatch */
        ProfilePatch: {
            /** Allergies */
            allergies?: string[];
            /** Conditions */
            conditions?: string[];
            /** Disliked Foods */
            disliked_foods?: string[];
            /** Goal */
            goal?: ("fat_loss" | "muscle_gain" | "stable_glucose") | null;
        };
        /** SafetyResult */
        SafetyResult: {
            /** Matched Rules */
            matched_rules?: string[];
            /**
             * Required Notice
             * @enum {string}
             */
            required_notice: "general" | "professional" | "emergency";
            /**
             * Risk Level
             * @enum {string}
             */
            risk_level: "S0" | "S1" | "S2" | "S3";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chat_stream_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Ordered SSE stream ending with a ChatFinalEvent payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Provider or evidence failure */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Provider not configured or unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
